export type NoUndefinedField<T> = { [P in keyof T]-?: NoUndefinedField<NonNullable<T[P]>> };

export type SparkleType = {
	id: string;
	createdAt: number;
	color: string;
	size: number;
	style: any;
};

export type TagType = {
	label: string;
	color?: 'primary' | 'secondary';
};

export type SocialLink = {};

export type Feature = {
	name: string;
	description: string;
	image: string;
	tags: TagType[];
};

// --- Backend-aligned Models ---

// Base Model (all have UUID id)
export interface BaseModel {
	id: string; // UUID
}

// UserDataModel
export interface UserDataModel extends BaseModel {
	email: string;
	authProvider: string;
	isAdmin: boolean;
	imagePath: string;
	userName: string;
	banned: boolean;
	ipAddress: string;
}

// UserContentModel
export interface UserContentModel extends BaseModel {
	userId: string; // UUID of the user
	comments: UserContentComment[];
	adminComments: UserContentAdminComment[]; // Separate array for admin comments
}

export interface UserContentComment {
	commentId: string; // UUID
	postId: string; // UUID of the post
	postTitle: string;
	section: string;
	text: string;
	date: string;
	adminComments?: UserContentAdminComment[]; // Optional nested admin comments
	deletedByAdmin?: boolean; // Flag for admin-deleted comments in user_content
}

export interface UserContentAdminComment {
	commentId: string; // UUID
	onComment: string; // UUID of the comment this admin comment is on
	postId: string; // UUID of the post
	postTitle: string;
	section: string;
	text: string;
	date: string;
}

// ContentModel (abstract, but used for News, etc.)
export interface ContentModel extends BaseModel {
	title: string;
	slug: string;
	date: string;
	coverImage: string;
	comments: PostComment[];
	excerpt: string;
	tags: string;
}

// ContentModel for updates (comments can be request type)
export interface ContentModelUpdate extends Omit<ContentModel, 'comments'> {
	comments: PostCommentRequest[];
}

// Comment data sent to backend (minimal fields)
export interface PostCommentRequest {
	userId: string; // UUID of the user
	text: string;
	date: string;
	adminComments?: PostAdminCommentRequest[]; // Optional nested admin comments
}

// Comment data received from backend (includes generated fields)
export interface PostComment {
	userId: string; // UUID of the user
	commentId: string; // UUID of the comment (generated by backend)
	text: string;
	date: string;
	adminComments?: PostAdminComment[]; // Optional nested admin comments
}

// Admin comment interfaces
export interface PostAdminCommentRequest {
	userId: string; // UUID of the admin
	onComment: string; // UUID of the comment this admin comment is on
	text: string;
	date: string;
}

export interface PostAdminComment {
	userId: string; // UUID of the admin
	commentId: string; // UUID of the admin comment
	onComment: string; // UUID of the comment this admin comment is on
	text: string;
	date: string;
}

// NewsContentModel
export interface NewsContentModel extends ContentModel {
	html: string;
}

// BannedUsersModel
export interface BannedUsersModel extends BaseModel {
	email: string;
	userId: string; // UUID of the user
	ipAddress: string;
}

// --- Deprecated/Legacy ---
// Use NewsContentModel or ContentModel instead
// export type BlogPost = { ... } // Deprecated
